config/routes.rb
Rails.application.routes.draw do
  root 'public/homes#top'

  devise_for :customers,skip: [:passwords], controllers: {
  sessions: 'public/sessions',
  registrations: 'public/registrations',
  }

  devise_for :admin, skip: [:registrations,:passwords] ,controllers: {
  sessions: 'admin/sessions'
  }

  namespace :admin do
    get '/admin' => 'homes#top'
    resources :items
    resources :customers
    resources :orders,only:[:index,:show,:update]
    resources :order_details, only: [:update]
  end

  namespace :public do
    get '/about' => 'homes#about'
    delete '/cart_items/all_destroy' => 'cart_items#destroy_all'
    resources :items, only: [:index, :show]
    get '/customers/edit' => 'customers#edit'
    patch '/customers/update' => 'customers#update'
    patch '/customers/out' => 'customers#out'
    get '/customers/quit' => 'customers#quit'
    get '/addresses/public' => 'addresses#index'

    resources :cart_items
    post '/orders' => 'orders#create'
    post '/orders/confirm' => 'orders#confirm'#注文情報確認画面の編集が終わったら、getからpostに戻すこと！
    get '/orders/thanx' => 'orders#thanx'
    resources :orders, only: [:new,:create,:show,:index]
    resource :customers, only:[:show ,:edit,:update]
    resources :shipping_addresses, only: [:index, :create, :destroy, :edit, :update]
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/addmin.rb
class Addmin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :customer
	belongs_to :item
	
	
	def subtotal
	 item.price*1.1.floor*cart_item.amount
	end
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         has_many :cart_items
         has_many :shipping_addresses
         has_many :orders
end

app/models/item.rb
class Item < ApplicationRecord
   has_many :cart_items
   has_many :order_items
   has_one_attached :image

   def tax_in_price
     (price*1.1).floor
   end
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  has_many :order_details
  enum payment_method: { credit_card: 0, transfer: 1 }
  enum status: {入金待ち:0, 入金確認:1, 製作中:2, 発送準備中:3, 発送済み:4}
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :order
	belongs_to :item
	enum making_status: {"着手不可": 0,"製作待ち": 1,"製作中": 2,"製作完了": 3}
end

app/models/shipping_address.rb
class ShippingAddress < ApplicationRecord
  belongs_to :customer

  def address_display
  '〒' + postal_code + ' ' + address + ' ' + name
  end
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  def index
  end

  def create
  end

  def edit
  end

  def update
  end
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  def top
    @orders = Order.all
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  def index
    @items = Item.all.page(params[:page]).per(10)
  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      redirect_to admin_item_path(@item)
    else
      render :new
    end
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
     if @item.update(item_params)
       redirect_to admin_item_path(@item)
     else
       render :edit
     end
  end

  private
  def item_params
    params.require(:item).permit(:image, :name, :introduction, :price, :is_active)
  end
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  def show
    @order = Order.find(params[:id])
    @order_details = @order.order_details
  end

  def update
    @order = Order.find(params[:id])
    @order.update(status: params[:order][:status])
    redirect_to admin_order_path(@order)

    if @order.status == "入金確認"
      @order.order_details.each do |order_detail|
        order_detail.update(making_status: 1)
      end
    end
  end

  private
  def order_params
    params.require(:order).permit(:shipping_cost,:total_payment,:name,:payment_method,:address,:postal_code,:status,:making_status)
  end

end

app/controllers/admin/sessions_controller.rb
# frozen_string_literal: true

class Admin::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  def after_sign_in_path_for(resource)
   admin_admin_path
  end

  def after_sign_out_path_for(resource)
    new_admin_session_path
  end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/admin/unlocks_controller.rb
# frozen_string_literal: true

class Admin::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/items/crete.html.erb
<h1>Admin::Items#crete</h1>
<p>Find me in app/views/admin/items/crete.html.erb</p>

app/views/admin/items/edit.html.erb
<div class="container">
<h2 class="text-center my-5">商品編集</h2>
<div class="row">
  <div class="col-8 offset-2 mb-5">
    <%= form_with model: @item, url: admin_item_path, local: true do |f| %>
     <table>
       <tr>
        <div class="form-group">
        <%= f.label :商品画像, class:"form_label"%>
        <%= f.file_field :image, accept: "image/*",class:"mb-3 ml-3" %>
        </div>
       </tr>
       <tr>
         <div class="form-group">
         <%= f.label :商品名, class:"form_label" %>
         <%= f.text_field :name, placeholder:"商品名",class:"form-control mb-3" %>
       </tr>
       <tr>
         <div class="form-group">
         <%= f.label :商品説明, class:"form_label" %>
         <%= f.text_area :introduction, size: "50x5", placeholder:"こちらに説明文を記述します",class:"form-control form-control-lg mb-3" %>
       </tr>
       <tr>
         <div class="form-group">
	       <%= f.label :税抜価格,class:"form_label" %>
	       <%= f.text_field :price, placeholder:"1000" %>円
       </tr>
       <tr>
         <div class="form-group">
         <%= f.label :販売ステータス,class:"form_label my-3" %>
         <%= f.radio_button :is_active, true, checked: true %>
         <%= f.label :is_active, "販売中",class:"form_label" %>
         <%= f.radio_button :is_active, false %>
         <%= f.label :is_active, "販売停止中",class:"form_label" %>
         </div>
         <div class="form-action d-flex justify-content-around">
         <%= f.submit '変更を保存', class:"btn btn-success" %>
         </div>
        </tr>
       <% end %>
     </table>
  </div>
</div>

app/views/admin/items/index.html.erb
<div class="container">
  <div class="row">
      <h1>商品一覧</h1>
  </div>

  <div class="row">
    <p><%= link_to "商品新規登録", new_admin_item_path, class: 'btn btn-success' %></p>
  </div>

    <div class="col-sm-2 px-sm-0 text-right mb-2">
      <%= link_to new_admin_item_path, class:"btn btn--circle btn--circle-c btn--shadow" do %>
      <% end %>
    </div>

  <div class="container">
    <div class="row">
      <div class="col-sm-10 px-sm-0 mx-auto mb-5">
      <table class="table text-center admin-items mb-5">
        <thead>
          <tr>
          <th>商品ID</th>
          <th>商品名</th>
          <th>税抜価格</th>
　　      <th>ステータス</th>
          </tr>
        </thead>
        <% @items.each do |item| %>
        <tbody>
          <tr>
            <td class="align-middle"><%= item.id %></td>
            <td class="align-middle"><%= link_to admin_item_path(item.id) do %>
              <u><%= item.name %></u>
            </td>
         <% end %>
         <td class="align-middle"><%= item.price %></td>
         <td class="align-middle"><% if item.is_active == true %>
           <p class="text-success font-weight-bold">販売中</p>
         <% else %>
           <p class="text-danger font-weight-bold">販売停止中</p>
         <% end %>
        </td>
       </tr>
      </tbody>
      <% end %>
    </table>
    <div class="mx-auto" style="width: 200px;">
      <%= paginate @items %>
    </div>
  </div>
</div>

app/views/admin/items/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-8 px-sm-0 offset-sm-1">
      <h2>商品新規登録</h2>
    </div>
  </div>
  <div class="row">
    <div class="col-sm-10 px-sm-0 mx-auto mb-5">
      <%= form_with model: @item, url: admin_items_path, local: true do |f| %>
      <table>
        <tr>
          <div class="form-group">
            <th><%= f.label :商品画像 %></th>
            <th><%= f.file_field :image, accept: "image/*" %></th>
          </div>
        </tr>
        <tr>
          <div class="form-group">
            <th><%= f.label :商品名 %></th>
            <td><%= f.text_field :name, placeholder:"商品名" %></td>
          </div>
        </tr>
        <tr>
          <div class="form-group">
            <th><%= f.label :商品説明 %></th>
            <td><%= f.text_area :introduction, size: "50x5", placeholder:"こちらに説明文を記述します" %></td>
          </div>
        </tr>
        <tr>
        <div class="form-group">
          <th><%= f.label :税抜価格 %></th>
          <td><%= f.text_field :price, placeholder:"1000" %>円</td>
        </div>
        </tr>
        <tr>
        <div class="form-group">
          <th><%= f.label :販売ステータス %></th>
          <td><%= f.radio_button :is_active, true, checked: true %>
              <%= f.label :is_active, "販売中" %>
              <%= f.radio_button :sis_active, false %>
              <%= f.label :is_active, "販売停止中" %>
          </td>
        </div>
        </tr>
        <tr>
        <div class="form-action">
          <th><%= f.submit "新規登録", class:"btn btn-success" %></th>
        </div>
        </tr>
      <% end %>
      </table>
    </div>
  </div>
</div>

app/views/admin/items/show.html.erb
<div class="container">
  <h2 class="mt-5 text-center">商品詳細</h2>
    <div class="row">

      <div class="row align-items-center m-5">
        <div class="col-lg text-center mb-5">
        <% if @item.image.attached? %>
        <%= image_tag @item.image, size: "300x250" %>
        <% else %>
        <%= image_tag 'no_image', size: "300x250" %>
        <% end %>
      </div>

      <div class="col-xs-6">
        <div class="info-content">
        <p class="info-head">商品名</p>
        <p class="item-info-text"><%= @item.name %></p>
      </div>

      <div class="info-content">
        <p class="info-head">商品説明</p>
        <p class="item-info-text"><%= simple_format(@item.introduction)%></p>
      </div>

      <div class="info-content">
        <p class="info-head">税込価格(税抜価格)</p>
        <p><%= @item.tax_in_price %> (<%= @item.price %>) 円</p>
        <p class="info-head">販売ステータス</p>
          <%  if @item.is_active == true %>
        <p class="text-success ">販売中</p>
          <% else %>
        <p class="text-secondary ">販売停止中</p>
          <% end %>
      </div>

        <div class="d-flex justify-content-around">
         <%= link_to "編集する", edit_admin_item_path(@item.id), class: 'btn btn-success' %>
        </div>
      </div>
    </div>
  </div>

app/views/admin/orders/show.html.erb
<div class="container">
  <h2 class="my-5 text-center">注文履歴詳細</h2>
  <div class="row justify-content-center">
    <div class="col-xs-12">
      <table class="table table-borderless">
         <thead>
            <tr><th>購入者</th><td><%= @order.name %></td></tr>
            <tr><th>注文日</th><td><%= @order.created_at.strftime("%Y-%m-%d %H:%M:%S")%></td></tr>
            <tr><th>配送先</th><td><%= "〒#{@order.postal_code}" %><br><%= @order.address %><br><%= @order.name %></td></tr>
            <tr><th>支払方法</th><td><%= @order.payment_method_i18n %></td></tr>
            <tr>
             <th>注文ステータス</th>
              <td>
                <%= form_with(model: @order, url: admin_order_path, method: :patch, local: true) do |f| %>
                <%= f.select :status, Order.statuses.keys,class:"status"%>
                <%= f.submit '更新', class:"btn btn-sm btn-success" %>
                <% end %>
              </td>
           </tr>
         </thead>
     </table>
    </div>
  </div>
  <div class="row justify-content-center">
    <div class="col-xs-8">
      <table class="table table-bordered">
        <thead class="thead-light">
          <tr>
            <th>商品名</th>
            <th>単価（税込）</th>
            <th>数量</th>
            <th>小計</th>
            <th>製作ステータス</th>
          </tr>
        </thead>
        <tbody>
          <% sum = 0 %>
          <% @order.order_details.each do |order_detail|%>
            <% sum += (order_detail.item.price*1.1).floor*order_detail.amount %>
            <tr>
              <td><p><%= order_detail.item.name%></p></td>
              <td><p><%= (order_detail.item.price*1.1).floor %></p></td>
              <td><p><%= order_detail.amount%></p></td>
              <td><p><%= (order_detail.item.price*1.1).floor*order_detail.amount %></p></td>
              <td>
                <%= form_with(model: order_detail, url: admin_order_detail_path(order_detail.id),method: :patch, local: true) do |f|%>
                <%= f.select :making_status, OrderDetail.making_statuses.keys, class:"making_status"%>
                <%= f.submit "更新", class:"btn btn-success"%>
                <% end %>
              </td>
            </tr>
            <% end %>
        </tbody>
      </table>
      <div class="col-xs-3 off-set-1">
      <table class="table">
          <tr>
            <th>送料</th>
            <td class="text-right col-xs-5">¥<%= @order.shipping_cost %></td>
          </tr>
          <tr>
            <th>商品合計</th>
            <td class="text-right col-xs-5">¥<%= sum %></td>
          </tr>
          <tr>
            <th>請求金額</th>
            <td class="text-right col-xs-5">¥<%= @order.total_payment %></td>
          </tr>
          <tr>
            <th></th>
            <td class="text-right col-xs-5"><%= link_to "注文履歴へ戻る",  admin_admin_path, class:"btn btn-outline-secondary"%></td>
          </tr>
      </table>
      </div>
    </div>
  </div>
</div>