config/routes.rb
Rails.application.routes.draw do
  root 'public/homes#top'

  devise_for :customers,skip: [:passwords], controllers: {
  sessions: 'public/sessions',
  registrations: 'public/registrations',
  }

  devise_for :admin, skip: [:registrations,:passwords] ,controllers: {
  sessions: 'admin/sessions'
  }

  namespace :admin do
    get '/admin' => 'homes#top'
    resources :items
    resources :customers
    resources :orders,only:[:index,:show,:update]
    resources :order_details, only: [:update]
  end

  namespace :public do
    get '/about' => 'homes#about'
    delete '/cart_items/all_destroy' => 'cart_items#destroy_all'
    resources :items, only: [:index, :show]
    get '/customers/edit' => 'customers#edit'
    patch '/customers/update' => 'customers#update'
    patch '/customers/out' => 'customers#out'
    get '/customers/quit' => 'customers#quit'
    get '/addresses/public' => 'addresses#index'

    resources :cart_items
    post '/orders' => 'orders#create'
    post '/orders/confirm' => 'orders#confirm'#注文情報確認画面の編集が終わったら、getからpostに戻すこと！
    get '/orders/thanx' => 'orders#thanx'
    resources :orders, only: [:new,:create,:show,:index]
    resource :customers, only:[:show ,:edit,:update]
    resources :shipping_addresses, only: [:index, :create, :destroy, :edit, :update]
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/addmin.rb
class Addmin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :customer
	belongs_to :item
	
	
	def subtotal
	 item.price*1.1.floor*cart_item.amount
	end
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         has_many :cart_items
         has_many :shipping_addresses
         has_many :orders
end

app/models/item.rb
class Item < ApplicationRecord
   has_many :cart_items
   has_many :order_items
   has_one_attached :image

   def tax_in_price
     (price*1.1).floor
   end
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  has_many :order_details
  enum payment_method: { credit_card: 0, transfer: 1 }
  enum status: {入金待ち:0, 入金確認:1, 製作中:2, 発送準備中:3, 発送済み:4}
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :order
	belongs_to :item
	enum making_status: {"着手不可": 0,"製作待ち": 1,"製作中": 2,"製作完了": 3}
end

app/models/shipping_address.rb
class ShippingAddress < ApplicationRecord
  belongs_to :customer

  def address_display
  '〒' + postal_code + ' ' + address + ' ' + name
  end
end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
  def index
    @customers = Customer.all.page(params[:page]).per(10)
  end

  def show
    @customer = Customer.find(params[:id])
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    @customer = Customer.find(params[:id])
    @customer.update(customer_params)
    redirect_to admin_customer_path
  end

  private
  def customer_params
    params.require(:customer).permit(:last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :telephone_number, :email, :is_deleted)
  end
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  def index
  end

  def create
  end

  def edit
  end

  def update
  end
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  def top
    @orders = Order.all
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  def index
    @items = Item.all.page(params[:page]).per(10)
  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      redirect_to admin_item_path(@item)
    else
      render :new
    end
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
     if @item.update(item_params)
       redirect_to admin_item_path(@item)
     else
       render :edit
     end
  end

  private
  def item_params
    params.require(:item).permit(:image, :name, :introduction, :price, :is_active)
  end
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  def show
    @order = Order.find(params[:id])
    @order_details = @order.order_details
  end

  def update
    @order = Order.find(params[:id])
    @order.update(status: params[:order][:status])
    redirect_to admin_order_path(@order)

    if @order.status == "入金確認"
      @order.order_details.each do |order_detail|
        order_detail.update(making_status: 1)
      end
    end
  end

  private
  def order_params
    params.require(:order).permit(:shipping_cost,:total_payment,:name,:payment_method,:address,:postal_code,:status,:making_status)
  end

end

app/controllers/admin/unlocks_controller.rb
# frozen_string_literal: true

class Admin::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/customers/edit.html.erb
<div class="container">

  <h2 class="text-center m-5"><%= @customer.last_name + @customer.first_name %>さんの会員詳細</h2>
  <div class="row d-flex justify-content-center">

  <%= form_with model: @customer, url: admin_customer_path(@customer.id), local: :true, method: :put do |f| %>
  <div class="col-xs-10 offset-1">
  <div class="form-group col-xs-9">
  <%= f.label :"会員ID", class: "col-sm-4" %>
  <%= f.label :"#{@customer.id}" %>
  </div>

　<div class="form-group col-xs-9">
  <%= f.label :氏名, class: "col-sm-4 control-label" %>
  <%= f.text_field :last_name, :size => "10", placeholder: "令和", class: "col-sm-3 form-control-static" %>
  <%= f.text_field :first_name, :size => "10", placeholder: "道子", class: "col-sm-3 form-control-static name" %>
  </div>

  <div class="form-group col-xs-9">
  <%= f.label :フリガナ, class: "col-sm-4 control-label" %>
  <%= f.text_field :last_name_kana, :size => "10", placeholder: "レイワ", class: "col-sm-3 form-control-static name" %>
  <%= f.text_field :first_name_kana, :size => "10", placeholder: "ミチコ", class: "col-sm-3 form-control-static name" %>
  </div>

  <div class="form-group col-xs-9">
  <%= f.label :メールアドレス, class: "col-sm-4 control-label" %>
  <%= f.email_field :email, :size => "25", placeholder: "sample@example.com", autofocus: true, autocomplete: "email", class: "col-sm-6" %>
  </div>

  <div class="form-group col-xs-9">
  <%= f.label :郵便番号, class: "col-sm-4 control-label" %>
  <%= f.text_field :postal_code, :size => "10", placeholder: "1001000", id: "customer_postcode", class: "col-sm-3" %>
  </div>

  <div class="form-group col-xs-9">
  <%= f.label :住所, class: "col-sm-4 control-label" %>
  <%= f.text_field :address, :size => "50", placeholder: "東京都渋谷区代々木神園町0-0", id: "customer_address", class: "col-sm-7" %>
  </div>

  <div class="form-group col-xs-9">
  <%= f.label :電話番号, class: "col-sm-4 control-label"%>
  <%= f.text_field :telephone_number, placeholder: "08012345678", class: "col-sm-4" %>
  </div>

  <div class="form-group col-xs-9">
  <%= f.label :会員ステータス, class: "col-sm-4 control-label" %>
  <%= f.radio_button :is_deleted, :false %>
  <%= f.label :is_deleted, "有効" %>
  <%= f.radio_button :is_deleted, :true %>
  <%= f.label :is_deleted, "退会" %>
  </div>

  <div class="form-group col-xs-9 d-flex justify-content-around">
  <%= f.submit "変更を保存",class: "btn btn-success" %>
  </div>
 <% end %>
 </div>
</div>

app/views/admin/customers/index.html.erb
<div class="container">
<h2 class="my-5">会員一覧</h2>

<table class="table">
  <thead>
    <tr>
      <th>会員ID</th>
      <th>氏名</th>
      <th>メールアドレス</th>
      <th>ステータス</th>
    </tr>
  </thead>

  <tbody>
    <% @customers.each do |customer| %>
    <tr>
      <td class="info col-xs-1">
        <%= customer.id %>
      </td>
      <td class="text-left">
        <%= link_to customer.last_name + customer.first_name, admin_customer_path(customer.id) %>
      </td>
      <td class="text-left">
        <%= customer.email %>
      </td>
      <td class="col-xs-2">
        <% if customer.is_deleted == false %>
          <p class="text-success">有効</p>
        <% else %>
          <p class="text-secondary">退会</p>
        <% end %>
      </td>
     </tr>
    <% end %>
  </tbody>
 </table>
 <div class="d-flex justify-content-center"><%= paginate(@customers)%></div>
</div>

app/views/admin/customers/show.html.erb
<div class="container">
  <h2 class="mt-5 text-center"><%= @customer.last_name + @customer.first_name %>さんの会員詳細</h2>
    <div class="row m-5">
      <div class="col-10 offset-1">
        <table class="table">
          <tr>
            <th class="text-center">会員ID</th>
             <td><%= @customer.id %></td>
          </tr>
          <tr>
            <th class="text-center">氏名</th>
             <td><%= @customer.last_name + @customer.first_name %></td>
          </tr>
          <tr>
            <th class="text-center">フリガナ</th>
              <td><%= @customer.last_name_kana + @customer.first_name_kana %></td>
          </tr>
          <tr>
            <th class="text-center">郵便番号</th>
              <td><%= @customer.postal_code %></td>
          </tr>
          <tr>
            <th class="text-center">住所</th>
              <td><%= @customer.address %></td>
          </tr>
          <tr>
            <th class="text-center">電話番号</th>
              <td><%= @customer.telephone_number %></td>
          </tr>
          <tr>
            <th class="text-center">メールアドレス</th>
              <td><%= @customer.email %></td>
          </tr>
          <tr>
            <th class="text-center">会員ステータス</th>
            <% if @customer.is_deleted == false %>
             <td class="text-success">有効</td>
            <% else %>
             <td class="text-secondary">退会</td>
            <% end %>
          </tr>
         </table>
         <div class="d-flex justify-content-around">
          <p><%= link_to "編集する", edit_admin_customer_path(@customer.id), class:"btn btn-success" %></p>
          <p><%= link_to "注文履歴一覧を見る", admin_admin_path, class:"btn btn-primary" %></p>
         </div>
        </div>
      </div>
    </div>