config/routes.rb
Rails.application.routes.draw do
  root 'public/homes#top'

  devise_for :customers,skip: [:passwords], controllers: {
  sessions: 'public/sessions',
  registrations: 'public/registrations',
  }

  devise_for :admin, skip: [:registrations,:passwords] ,controllers: {
  sessions: 'admin/sessions'
  }

  namespace :admin do
    get '/admin' => 'homes#top'
    resources :items
    resources :customers
    resources :orders,only:[:index,:show,:update]
    resources :order_details, only: [:update]
  end

  namespace :public do
    get '/about' => 'homes#about'
    delete '/cart_items/all_destroy' => 'cart_items#destroy_all'
    resources :items, only: [:index, :show]
    get '/customers/edit' => 'customers#edit'
    patch '/customers/update' => 'customers#update'
    patch '/customers/out' => 'customers#out'
    get '/customers/quit' => 'customers#quit'
    get '/addresses/public' => 'addresses#index'

    resources :cart_items
    post '/orders' => 'orders#create'
    post '/orders/confirm' => 'orders#confirm'#注文情報確認画面の編集が終わったら、getからpostに戻すこと！
    get '/orders/thanx' => 'orders#thanx'
    resources :orders, only: [:new,:create,:show,:index]
    resource :customers, only:[:show ,:edit,:update]
    resources :shipping_addresses, only: [:index, :create, :destroy, :edit, :update]
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/addmin.rb
class Addmin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :customer
	belongs_to :item
	
	
	def subtotal
	 item.price*1.1.floor*cart_item.amount
	end
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         has_many :cart_items
         has_many :shipping_addresses
         has_many :orders
end

app/models/item.rb
class Item < ApplicationRecord
   has_many :cart_items
   has_many :order_items
   has_one_attached :image

   def tax_in_price
     (price*1.1).floor
   end
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  has_many :order_details
  enum payment_method: { credit_card: 0, transfer: 1 }
  enum status: {入金待ち:0, 入金確認:1, 製作中:2, 発送準備中:3, 発送済み:4}
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :order
	belongs_to :item
	enum making_status: {"着手不可": 0,"製作待ち": 1,"製作中": 2,"製作完了": 3}
end

app/models/shipping_address.rb
class ShippingAddress < ApplicationRecord
  belongs_to :customer

  def address_display
  '〒' + postal_code + ' ' + address + ' ' + name
  end
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  def index
  end

  def create
  end

  def edit
  end

  def update
  end
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  def top
    @orders = Order.all
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  def index
    @items = Item.all.page(params[:page]).per(10)
  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      redirect_to admin_item_path(@item)
    else
      render :new
    end
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
     if @item.update(item_params)
       redirect_to admin_item_path(@item)
     else
       render :edit
     end
  end

  private
  def item_params
    params.require(:item).permit(:image, :name, :introduction, :price, :is_active)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title class="text-success">NaganoCake</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

<body class="d-flex flex-column vh-100">
  <header class="shadow-sm">
    <nav class="navbar navbar-expand-lg navbar-light">
      <div class="container">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <div class="nav-item"><%= link_to 'ながのCAKE', root_path %></div>
            <ul class="navbar-nav ml-auto">
              <% if customer_signed_in? %>
                <li id="youkoso">ようこそ、<%= current_customer.last_name %>さん！</li>
                <li class="nav-item"><%= link_to public_customers_path(current_customer) do %>マイページ<% end %></li>
                <li class="nav-item"><%= link_to public_items_path do %>商品一覧<% end %></li>
                <li class="nav-item"><%= link_to public_cart_items_path do %><%= current_customer.cart_items.count %>カート<% end %></li>
                <li class="nav-item"><%= link_to destroy_customer_session_path, method: :delete do %>ログアウト<% end %></li>

              <% elsif admin_signed_in?%>
                <li class="nav-item"><%= link_to ' 商品一覧', admin_items_path %></li>
                <li class="nav-item"><%= link_to ' 会員一覧', admin_customers_path %></li>
                <li class="nav-item"><%= link_to ' 注文履歴一覧', admin_admin_path %></li>
                <li class="nav-item"><%= link_to ' ログアウト', destroy_admin_session_path, method: :delete %></li>

              <% else %>
                <li class="nav-item"><%= link_to public_about_path do %>About<% end %></li>
                <li class="nav-item"><%= link_to public_items_path do %>商品一覧<% end %></li>
                <li class="nav-item"><%= link_to new_customer_registration_path do %>新規登録<% end %></li>
                <li class="nav-item"><%= link_to new_customer_session_path do %>ログイン<% end %></li>
              <% end %>
            </ul>
          </div>
      </div>
    </nav>
  </header>


 　  <main id="content">
    <%= yield %>
   </main>

  </body>
</html>